DWAPlannerROS:
  max_vel_x: 2.5
  min_vel_x: -0.3
  max_vel_theta: 2.0
  min_vel_theta: -2.0
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  sim_time: 2.0
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.02
